### ISSUE TITLE
TECHNICAL: migrate from Airtable to MongoDB

### ISSUE THREAD

**Issue by arrested-developer** [yalla-coop/rent-check#19]
- [x] getLocations function retrieves location from database
- [ ] users can add data via a form (#21)
- [ ] new data has geolocation added when adding to database

**Comment by arrested-developer** [comment]
closing as replaced by milestone, this is too epic
