### ISSUE TITLE
AS AN administrator I NEED TO view all users stored in the database SO THAT I can manage their access and data

### ISSUE THREAD

**Issue by arrested-developer** [yalla-coop/rent-check#6]
- [ ] I can see a table of all users stored in the database
- [ ] I can see each user's role
- [ ] I can see if a user has access to the app or not

**Comment by dupreesi** [comment]
**tasks**
- [ ] query User model to get ALL USERS 
- [ ] process array of users so that it renders correctly in Admin Panel's Users Section
- [ ]render Approve / Reject buttons (without functionality)like in Figma
