### ISSUE TITLE
AS AN administrator I NEED TO grant and remove admin or super-user privileges to other users SO THAT they can also access the administration panel

### ISSUE THREAD

**Issue by arrested-developer** [yalla-coop/rent-check#7]
- [ ] I can grant admin privileges
- [ ] I can grant super-user privileges
- [ ] I can view a list of all users with admin or super-user privileges
- [ ] I can revoke admin privileges
- [ ] I can revoke super-user privileges

**Comment by dupreesi** [comment]
@arrested-developer: 
can the admin user grant super user privileges to all verified users or only to those awaiting SuperUser status?

**Comment by arrested-developer** [comment]
>can the admin user grant super user privileges to all verified users or only to those awaiting SuperUser status?

to any verified user

>does it make sense to create a status that indicates that a user has previously been rejected super user privileges?

For now, no, let's keep this really simple. If the request for super user is rejected then they go back to `verified`. I think if we were to improve this system later, perhaps we might need a requests collection so we can track what happens

**Comment by dupreesi** [comment]
**tasks**
- [ ] setup query to deal with approve and reject functions updating user model accordingly
- [ ] setup handler to process request, query and response
- [ ] setup usePatch custom hook 
- [ ] send request from REACT component
- [ ] handle response in REACT component
