### ISSUE TITLE
AS A developer I NEED TO work with an Express server SO THAT I feel confident that authentication is handled securely

### ISSUE THREAD

**Issue by arrested-developer** [yalla-coop/rent-check#87]
User routes

- [x] getLocations is refactored to GET request at `/api/locations`
- [x] addLocation is refactored to POST request at `/api/locations`
- [ ] getRentalRecordAddedByAdmin is refactored to GET request at `/api/locations/:userId` - this doesn't need to be an admin route as it will also be needed to return any data a normal user has submitted

Admin routes

- [ ] getRentalData is refactored to GET request at `/api/admin/locations`
- [ ] getUsers is refactored to GET request at `api/admin/users`
- [ ] manageUserStatus is refactored to PATCH request at `api/admin/users/:userID`

Tests

- [x] frontend tests all passing
- [ ] handler tests refactored to route tests and passing
- [ ] database query tests refactored and passing

**Comment by arrested-developer** [comment]
Test coverage in monorepo requires separate submissions and flags
https://docs.codecov.io/docs/flags
